### ISSUE TITLE
pacbrew.mydedibox.fr is down?

### ISSUE THREAD

**Issue by glebm** [PacBrew/pacbrew-packages#6]
Our CI has been failing for about a week: https://github.com/diasurgical/devilutionX/actions/runs/12002102581/job/33453563597

**Comment by glebm** [comment]
Ah, I see it's changed to pacman.mydedibox.fr.

Perhaps a new https://github.com/PacBrew/pacbrew-pacman release is needed?
Or should we switch to vanilla pacman in CI?

**Comment by Cpasjuste** [comment]
Hi mate,

Sorry for all this crap. I moved my server to a new host, and I took the opportunity to cleanup pacbrew "stuff" a little (changing dns subdomain as you discovered and adding https). I also added Ubuntu 24.04 instructions to pacbrew-packages readme (https://github.com/PacBrew/pacbrew-packages).

Please let me know if all is working fine for you !

Edit: yes it seems it is, thanks for the report anyway !

**Comment by glebm** [comment]
OK thanks for confirming, no problem!
